### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by wifi75** [Daveiano/weewx-wdc#122]
hello after send this command: wee_extension --install /tmp/weewx-wdc/

return this error as below

```
root@ubuntu-server:/etc/weewx# wee_extension --install /tmp/weewx-wdc/
Request to install '/tmp/weewx-wdc/'
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 92, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 84, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 137, in install_extension
    self.install_from_dir(extension_path)
  File "/usr/share/weewx/weecfg/extension.py", line 150, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 1897, in get_extension_installer
    __import__('install')
  File "/tmp/weewx-wdc/install.py", line 3
SyntaxError: Non-ASCII character '\xc3' in file /tmp/weewx-wdc/install.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
root@ubuntu-server:/etc/weewx#
```

**Comment by Daveiano** [comment]
Could you paste the output of `cat /tmp/weewx-wdc/install.py` here?

> SyntaxError: Non-ASCII character '\xc3' in file /tmp/weewx-wdc/install.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

So encoding is messed up here at some point, but not sure whats the place to look. Is your weewx installation running and working with other Skins?

**Comment by wifi75** [comment]
> cat /tmp/weewx-wdc/install.py

```
root@ubuntu-server:~# cat /tmp/weewx-wdc/install.py
from weecfg.extension import ExtensionInstaller

# Copyright 2023 David Bätge
# Distributed under the terms of the GNU Public License (GPLv3)


def loader():
    return BasicInstaller()


class BasicInstaller(ExtensionInstaller):
    def __init__(self):
        super(BasicInstaller, self).__init__(
            version="3.0.0",
            name="weewx-wdc",
            description="Weather Data Center skin for WeeWX.",
            author="David Baetge",
            author_email="david.baetge@gmail.com",
            config={
                "StdReport": {
                    "WdcReport": {
                        "skin": "weewx-wdc",
                        "enable": "true",
                        "lang": "en",
                        # 'unit_system': 'US'
                    }
                }
            },
            files=[
                (
                    "bin/user",
                    [
                        "bin/user/weewx_wdc.py",
                    ],
                ),
                (
                    "skins/weewx-wdc",
                    [
                        "skins/weewx-wdc/index.html.tmpl",
                        "skins/weewx-wdc/yesterday.html.tmpl",
                        "skins/weewx-wdc/week.html.tmpl",
                        "skins/weewx-wdc/month.html.tmpl",
                        "skins/weewx-wdc/dwd.html.tmpl",
                        "skins/weewx-wdc/day-archive/day-%Y-%m-%d.html.tmpl",
                        "skins/weewx-wdc/month-%Y-%m.html.tmpl",
                        "skins/weewx-wdc/NOAA/NOAA-%Y-%m.txt.tmpl",
                        "skins/weewx-wdc/year.html.tmpl",
                        "skins/weewx-wdc/NOAA/NOAA-%Y.txt.tmpl",
                        "skins/weewx-wdc/year-%Y.html.tmpl",
                        "skins/weewx-wdc/statistics.html.tmpl",
                        "skins/weewx-wdc/celestial.html.tmpl",
                        "skins/weewx-wdc/about.html.tmpl",
                        "skins/weewx-wdc/offline.html.tmpl",
                        "skins/weewx-wdc/manifest.json",
                        "skins/weewx-wdc/icon-192x192.png",
                        "skins/weewx-wdc/icon-256x256.png",
                        "skins/weewx-wdc/icon-384x384.png",
                        "skins/weewx-wdc/icon-512x512.png",
                        "skins/weewx-wdc/skin.conf",
                        "skins/weewx-wdc/lang/de.conf",
                        "skins/weewx-wdc/lang/en.conf",
                        "skins/weewx-wdc/lang/it.conf",
                        "skins/weewx-wdc/service-worker.js",
                        "skins/weewx-wdc/dist/main.css",
                        "skins/weewx-wdc/dist/main.js",
                        "skins/weewx-wdc/dist/assets/IBMPlexMono-Regular.woff2",
                        "skins/weewx-wdc/dist/assets/IBMPlexMono-Regular.woff",
                        "skins/weewx-wdc/dist/assets/IBMPlexSans-Regular.woff2",
                        "skins/weewx-wdc/dist/assets/IBMPlexSans-Regular.woff",
                        "skins/weewx-wdc/dist/assets/IBMPlexSans-SemiBold.woff2",
                        "skins/weewx-wdc/dist/assets/IBMPlexSans-SemiBold.woff",
                        "skins/weewx-wdc/dist/assets/IBMPlexSerif-Regular.woff2",
                        "skins/weewx-wdc/dist/assets/IBMPlexSerif-Regular.woff",
                        "skins/weewx-wdc/favicon.ico",
                        "skins/weewx-wdc/plotly-custom-build.min.js",
                        "skins/weewx-wdc/includes/html-head.inc",
                        "skins/weewx-wdc/includes/almanac-tile.inc",
                        "skins/weewx-wdc/includes/almanac-tile-simple.inc",
                        "skins/weewx-wdc/includes/almanac-moon-detail-tile.inc",
                        "skins/weewx-wdc/includes/almanac-sun-detail-tile.inc",
                        "skins/weewx-wdc/includes/combined-diagram-tile.inc",
                        "skins/weewx-wdc/includes/data-table-tile.inc",
                        "skins/weewx-wdc/includes/diagram-tile.inc",
                        "skins/weewx-wdc/includes/diagram-tile-wind-rose.inc",
                        "skins/weewx-wdc/includes/dwd-warning.inc",
                        "skins/weewx-wdc/includes/stat-tile.inc",
                        "skins/weewx-wdc/includes/conditions-table.inc",
                        "skins/weewx-wdc/includes/climatological-days.inc",
                        "skins/weewx-wdc/includes/ui-shell.inc",
                        "skins/weewx-wdc/includes/footer.inc",
                        "skins/weewx-wdc/includes/body-classic.inc",
                        "skins/weewx-wdc/includes/body-alternative.inc",
                        "skins/weewx-wdc/includes/forecast.inc",
                        "skins/weewx-wdc/includes/forecast-table.inc",
                        "skins/weewx-wdc/includes/icons/barometer.svg",
                        "skins/weewx-wdc/includes/pictograms/sun.svg",
                        "skins/weewx-wdc/includes/pictograms/moon.svg",
                        "skins/weewx-wdc/includes/icons/battery.svg",
                        "skins/weewx-wdc/includes/icons/signal.svg",
                        "skins/weewx-wdc/includes/icons/soil-moist.svg",
                        "skins/weewx-wdc/includes/icons/soil-temp.svg",
                        "skins/weewx-wdc/includes/icons/lightning.svg",
                        "skins/weewx-wdc/includes/icons/noise.svg",
                        "skins/weewx-wdc/includes/icons/voltage.svg",
                        "skins/weewx-wdc/includes/icons/forecast.svg",
                        "skins/weewx-wdc/includes/icons/leaf.svg",
                        "skins/weewx-wdc/includes/icons/hail.svg",
                        "skins/weewx-wdc/includes/icons/snow.svg",
                        "skins/weewx-wdc/includes/icons/snow-depth.svg",
                        "skins/weewx-wdc/includes/icons/snow-moist.svg",
                        "skins/weewx-wdc/includes/icons/cloud-base.svg",
                        "skins/weewx-wdc/includes/icons/dew-point.svg",
                        "skins/weewx-wdc/includes/icons/et.svg",
                        "skins/weewx-wdc/includes/icons/app-temp.svg",
                        "skins/weewx-wdc/includes/icons/heat-index.svg",
                        "skins/weewx-wdc/includes/icons/humidity.svg",
                        "skins/weewx-wdc/includes/icons/rain-rate.svg",
                        "skins/weewx-wdc/includes/icons/rain.svg",
                        "skins/weewx-wdc/includes/icons/radiation.svg",
                        "skins/weewx-wdc/includes/icons/temp.svg",
                        "skins/weewx-wdc/includes/icons/uv.svg",
                        "skins/weewx-wdc/includes/icons/wind-chill.svg",
                        "skins/weewx-wdc/includes/icons/wind-run.svg",
                        "skins/weewx-wdc/includes/icons/wind-direction.svg",
                        "skins/weewx-wdc/includes/icons/wind-direction.inc",
                        "skins/weewx-wdc/includes/icons/wind-gust.svg",
                        "skins/weewx-wdc/includes/icons/wind-speed.svg",
                        "skins/weewx-wdc/includes/icons/sunrise.svg",
                        "skins/weewx-wdc/includes/icons/sunset.svg",
                        "skins/weewx-wdc/includes/icons/moon.svg",
                        "skins/weewx-wdc/includes/icons/moonrise.svg",
                        "skins/weewx-wdc/includes/icons/moonset.svg",
                        "skins/weewx-wdc/includes/icons/github.svg",
                        "skins/weewx-wdc/includes/icons/wdc.svg",
                        "skins/weewx-wdc/includes/icons/forecast/B1.svg",
                        "skins/weewx-wdc/includes/icons/forecast/B2.svg",
                        "skins/weewx-wdc/includes/icons/forecast/BK.svg",
                        "skins/weewx-wdc/includes/icons/forecast/CL.svg",
                        "skins/weewx-wdc/includes/icons/forecast/FW.svg",
                        "skins/weewx-wdc/includes/icons/forecast/OV.svg",
                        "skins/weewx-wdc/includes/icons/forecast/SC.svg",
                        "skins/weewx-wdc/includes/icons/forecast/rain.svg",
                        "skins/weewx-wdc/includes/icons/forecast/snow.svg",
                        "skins/weewx-wdc/includes/icons/forecast/sleet.svg",
                        "skins/weewx-wdc/includes/icons/forecast/fog.svg",
                        "skins/weewx-wdc/includes/icons/forecast/haze.svg",
                        "skins/weewx-wdc/includes/icons/forecast/snow--scattered.svg",
                        "skins/weewx-wdc/includes/icons/forecast/rain--scattered.svg",
                        "skins/weewx-wdc/includes/icons/forecast/thunderstorm.svg",
                        "skins/weewx-wdc/includes/icons/forecast/thunderstorm--scattered.svg",
                    ],
                ),
            ],
        )
```

**Comment by Daveiano** [comment]
Sorry for the late response, here are some hints:

I suspect you are using Python 3?

Did you follow exactly the installation instructions?

```
wget -O "/tmp/weewx-wdc.zip" https://github.com/Daveiano/weewx-wdc/releases/download/v3.0.0/weewx-wdc-v3.0.0.zip &&\
mkdir /tmp/weewx-wdc/ &&\
unzip /tmp/weewx-wdc.zip -d /tmp/weewx-wdc/ &&\
sudo wee_extension --install /tmp/weewx-wdc/
```

If so, could you please try again? 

Sorry, but this must be something with your local setup, there are no complains from other users and I installed it myself multiple times.

There is also a Dockerfile if this helps somehow: https://github.com/Daveiano/weewx-wdc-interceptor-docker/blob/main/Dockerfile

**Comment by wifi75** [comment]
Hello my Python versin is : 2.7.17

**Comment by Daveiano** [comment]
I'm sorry again for not getting back to you sooner. 

So I think I found the reason for that. Could you please, before you run the install command, change Line 3 of `install.py` from

`# Copyright 2023 David Bätge`

to 

`# Copyright 2023 David Baetge` (or remove Line 3 completely for testing).

This should already solve the problem. It seems Python 2.x uses ASCII as default encoding, while Python 3.x uses UTF8.

**Comment by wifi75** [comment]
oh yes installation occured !
but the configuration below it is correct?



```
    [[SeasonsReport]]
        # The SeasonsReport uses the 'Seasons' skin, which contains the
        # images, templates and plots for the report.
        skin = Seasons
        enable = true
    
    [[SmartphoneReport]]
        # The SmartphoneReport uses the 'Smartphone' skin, and the images and
        # files are placed in a dedicated subdirectory.
        skin = Smartphone
        enable = false
        HTML_ROOT = /var/www/html/weewx/smartphone
    
    [[MobileReport]]
        # The MobileReport uses the 'Mobile' skin, and the images and files
        # are placed in a dedicated subdirectory.
        skin = Mobile
        enable = false
        HTML_ROOT = /var/www/html/weewx/mobile
    
    [[StandardReport]]
        # This is the old "Standard" skin. By default, it is not enabled.
        skin = Standard
        enable = true
   
    [[WdcReport]]
        lang = it
        enable = true
        skin = weewx-wdc
    
```                                             ls

I keep seeing the old weewx skyn all the time

**Comment by Daveiano** [comment]
Ok, as a second test, please add this as first line to weewx_wdc.py (in User directory, see https://weewx.com/docs/usersguide.htm#Where_to_find_things)

`# coding: utf-8`

This should resolve the error and generate the skin files.

**Comment by wifi75** [comment]
like below?
![image](https://user-images.githubusercontent.com/31816231/224490836-9bde8987-d274-4c3b-a77e-447b5df9b991.png)

after sto weewx I send this command_

wee_reports

return:

```
Generating as of last timestamp in the database.
Using configuration file /etc/weewx/weewx.conf
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 166, in run
    self.init_extensions(gen_dict[section_name])
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in init_extensions
    klass = weeutil.weeutil.get_object(x)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1335, in get_object
    mod = __import__(module)
  File "/usr/share/weewx/user/weewx_wdc.py", line 45
    syslog.syslog(level, F'jas: {msg}')
                                     ^
SyntaxError: invalid syntax
root@ubuntu-server:~#
```

**Comment by Daveiano** [comment]
Oh there are some more compatibility issues here, could you please also change line 45 to

`syslog.syslog(level, 'weewx-wdc: %s' % msg)`

Sorry for all the changes and tests. If these changes fix the problem, I will release a new version with these changes included soon, so you do not have to do this manually.

**Comment by wifi75** [comment]
where is the new 3.1.0 version?

**Comment by Daveiano** [comment]
Not yet been released. 

Can you verify that the change from my previous comment resolves the problem?

**Comment by wifi75** [comment]
some problem

**Comment by wifi75** [comment]
this below  it is correct?
![image](https://user-images.githubusercontent.com/31816231/224529981-7f45269f-e7d5-4568-bea2-881357085fa7.png)

**Comment by wifi75** [comment]
the problem is that the default skin always appears
see
https://meteo.iu3cyv.eu/weewx/

this is my config :

```
#   This section specifies what reports, using which skins, to generate.

[StdReport]
    
    # Where the skins reside, relative to WEEWX_ROOT
    SKIN_ROOT = /etc/weewx/skins
    
    
    # Where the generated reports should go, relative to WEEWX_ROOT
    HTML_ROOT = /var/www/html/weewx
    
    # The database binding indicates which data should be used in reports.
    data_binding = wx_binding
    
    # Whether to log a successful operation
    log_success = True
    
    # Whether to log an unsuccessful operation
    log_failure = True
    
    # Each of the following subsections defines a report that will be run.
    # See the customizing guide to change the units, plot types and line
    # colors, modify the fonts, display additional sensor data, and other
    # customizations. Many of those changes can be made here by overriding
    # parameters, or by modifying templates within the skin itself.
    
    [[SeasonsReport]]
        # The SeasonsReport uses the 'Seasons' skin, which contains the
        # images, templates and plots for the report.
        skin = Standard
        enable = true
    
    [[SmartphoneReport]]
        # The SmartphoneReport uses the 'Smartphone' skin, and the images and
        # files are placed in a dedicated subdirectory.
        skin = Smartphone
        enable = false
        HTML_ROOT = /var/www/html/weewx/smartphone
    
    [[MobileReport]]
        # The MobileReport uses the 'Mobile' skin, and the images and files
        # are placed in a dedicated subdirectory.
        skin = Mobile
        enable = false
        HTML_ROOT = /var/www/html/weewx/mobile
    
    [[StandardReport]]
        # This is the old "Standard" skin. By default, it is not enabled.
        skin = Standard
        enable = true
    [[WdcReport]]
        lang = it
        enable = true
        skin = weewx-wdc
```

**Comment by Daveiano** [comment]
Yes, your changes are correct and your config is also correct.

Are there any errors in the log when running `wee_reports` now?

Sorry, I am currently struggling to deploy a python2 environment to test this by myself.

**Comment by wifi75** [comment]
yes the error after wee_reports  it is same like Post before

**Comment by wifi75** [comment]
this

```
Generating as of last timestamp in the database.
Using configuration file /etc/weewx/weewx.conf
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 166, in run
    self.init_extensions(gen_dict[section_name])
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in init_extensions
    klass = weeutil.weeutil.get_object(x)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1335, in get_object
    mod = __import__(module)
  File "/usr/share/weewx/user/weewx_wdc.py", line 45
    syslog.syslog(level, F'jas: {msg}')
                                     ^
SyntaxError: invalid syntax
root@ubuntu-server:~#
```

**Comment by Daveiano** [comment]
Oh then the change was done in the wrong file, because 

`syslog.syslog(level, F'jas: {msg}')`

should be replaced by 

`syslog.syslog(level, 'weewx-wdc: %s' % msg)`

in File "/usr/share/weewx/user/weewx_wdc.py", line 45

**Comment by Daveiano** [comment]
~[weewx_wdc.py.txt](https://github.com/Daveiano/weewx-wdc/files/10951919/weewx_wdc.py.txt)~

Here is the the corrected file, just rename it to `weewx_wdc.py` and copy to `/usr/share/weewx/user/`


**SORRY** this was the wrong file, that's the right one: [weewx_wdc.py.txt](https://github.com/Daveiano/weewx-wdc/files/10951935/weewx_wdc.py.txt)

**Comment by wifi75** [comment]
> ~[weewx_wdc.py.txt](https://github.com/Daveiano/weewx-wdc/files/10951919/weewx_wdc.py.txt)~
> 
> Here is the the corrected file, just rename it to `weewx_wdc.py` and copy to `/usr/share/weewx/user/`
> 
> **SORRY** this was the wrong file, that's the right one: [weewx_wdc.py.txt](https://github.com/Daveiano/weewx-wdc/files/10951935/weewx_wdc.py.txt)

same problem after update new file

```
root@ubuntu-server:~# wee_reports
Generating as of last timestamp in the database.
Using configuration file /etc/weewx/weewx.conf
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 166, in run
    self.init_extensions(gen_dict[section_name])
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in init_extensions
    klass = weeutil.weeutil.get_object(x)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1335, in get_object
    mod = __import__(module)
  File "/usr/share/weewx/user/weewx_wdc.py", line 743
    return {**dwd_warnings.get("counties", {}), **dwd_warnings.get("cities", {})}
             ^
SyntaxError: invalid syntax
```

**Comment by Daveiano** [comment]
Ok sorry, this is another Python 2 compatibility problem. It seems, there are too many incompatibilities and Python 2 is End of Life since 2020, so it feels weird to support a so outdated version. 

Please update your system to Python 3 in order to use the skin, I will add this as a requirement to the readme.
