### ISSUE TITLE
[BUG] Syntax error returned by reportengine

### ISSUE THREAD

**Issue by NikoFresh** [Daveiano/weewx-wdc#135]
I've just installed, for the first time, the v3.0.1 of the skin following the instructions on the readme. The only change i've done was setting the base path to a subdirectory since the website is already running on another skin for now.

Relevant weewx log:
```
Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****  invalid syntax (weewx_wdc.py, line 743)
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****      obj.start()
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****      self.run()
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 166, in run
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****      self.init_extensions(gen_dict[section_name])
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in init_extensions
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****      klass = weeutil.weeutil.get_object(x)
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1335, in get_object
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****      mod = __import__(module)
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/weewx_wdc.py", line 743
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****      return {**dwd_warnings.get("counties", {}), **dwd_warnings.get("cities", {})}
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****               ^
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****  SyntaxError: invalid syntax
Mar 22 16:15:22 raspberrypi weewx[2485] ERROR weewx.reportengine:         ****  Generator terminated
Mar 22 16:15:22 raspberrypi weewx[2485] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/wdc
```

On skin.conf everything related to DWD forecast is commented out.

Weewx version: 4.10.2
Python version: 3.7.3

**Comment by Daveiano** [comment]
Are you sure about running Python 3?

Another user had the same error message with python 2 here: https://github.com/Daveiano/weewx-wdc/issues/122#issuecomment-1465308164 which seems to be the same error message.

**Comment by NikoFresh** [comment]
To me it looks like python3 is running as default
```
pi@raspberrypi:~ $ python --version
Python 3.7.3
pi@raspberrypi:~ $ which python
/usr/bin/python
pi@raspberrypi:~ $ ls -lart /usr/bin/python
lrwxrwxrwx 1 root root 18 mar 23 11:08 /usr/bin/python -> /usr/bin/python3.7
```
I have also python2 installed on the system but it shouldn't be a problem

**Comment by Daveiano** [comment]
Could you please include the start of your log? 

There should be a line telling the python version, something like:

```
Mar 24 00:49:52 dba-MS-7D07 weewx[172338] INFO __main__: Initializing weewx version 4.10.1
Mar 24 00:49:52 dba-MS-7D07 weewx[172338] INFO __main__: Using Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Mar 24 00:49:52 dba-MS-7D07 weewx[172338] INFO __main__: Located at /bin/python3
Mar 24 00:49:52 dba-MS-7D07 weewx[172338] INFO __main__: Platform Linux-5.19.0-35-generic-x86_64-with-glibc2.35
```

Python 2 is the only clue I have since the double star/asterisk operator (`**`) used for dict unpacking is a Python 3 feature as far as I know, so this error message only makes sense with Python 2.

**Comment by NikoFresh** [comment]
Turns out weewx was actually running on python 2. Apparently if you installed it while running python2 you have to reinstall it, even though python3 is mandatory since some time even for weewx itself. 
Sorry for bothering you and thanks for the awesome work on the skin.

**Comment by Daveiano** [comment]
No problem! I was sure about this being a python 2 problem ;)
