### ISSUE TITLE
[BUG] Crash after upgrade to 3.1.1

### ISSUE THREAD

**Issue by endmarsfr** [Daveiano/weewx-wdc#150]
when i upgraded to weewx-wdc skin 3.1.1 with weewx 4.10.1 and weewx 4.10.2, weewx crashs with this error
if i rollback to weewx-wdc skin 3.0.1 everything works fine.

for information, I used : [MQTTSubscribeDriver] in weewx.conf

```
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/index.html.tmpl failed with exception '<class 'KeyError'>'
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/index.html.tmpl
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: **** Reason: 'mqtt'
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 348, in generate
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_index_html_tmpl.py", line 230, in respond
avril 06 13:01:29 radio weewxd[143518]: weewx[143518] ERROR weewx.cheetahgenerator: ****  KeyError: 'mqtt'

```

**Comment by Daveiano** [comment]
Your skin.conf seems to be missing the mqtt configuration (https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/skin.conf#L34)

```
[Extras]
    ...
     [[mqtt]]
        mqtt_websockets_enabled = 0
        mqtt_websockets_host = "localhost"
        mqtt_websockets_port = 9001
        mqtt_websockets_ssl = 0
        mqtt_websockets_topic = "weather/loop"
```

This section should be available in the `[Extras]` section of your skin.conf. Did you remove it manually or do you use an old skin.conf backup file somehow?

**Comment by endmarsfr** [comment]
My apologizes 
you're rigth.
I had reused a previous skin.conf  file
Thanks you for the support
